# Generated by Django 3.1.5 on 2021-04-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('longitude', models.FloatField(unique=True)),
                ('latitude', models.FloatField(unique=True)),
                ('speciality', models.CharField(max_length=255)),
            ],
        ),
    ]
