# Generated by Django 3.1.5 on 2021-04-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
